### ISSUE TITLE
feat(chore): Test, Comment then publish to npm

### ISSUE THREAD

**Issue by maissani** [trailsjs/trailpack-cache#1]
# Trailpack-Cache
### Introduction

This is the alpha version of trailpack-cache.
This issue aim to publish the cache system, 
If you have any comments, claim unit testing before you can ask it there.
If you think that it's all good, then publish it to npm.
#### Stores
- [x] Memory Store
- [x] Redis Store
- [x] Mongoose Store
- [x] Fs Store
- [x] Fs Binary Store
- [ ] Hazelcast Store (Disabled: referenced as the issue #3: work on node v6 but not on v4 and v5)
#### Features
- [x] Single Store Usage
- [ ] Multiple Store Usage
# This trailpack is waiting for approbation

Don't forget to remove readme warning at line2 ("WARING : The current version of this trailpack is not available")

**Comment by jaumard** [comment]
You need to add a `config/caches.js` if you want to be compatible with merge-env :) 
You can initialize the travis.yml files and let @tjwebb put the token for automatic deployment.
Missing Contributing and Licence section on the readme :)

**Comment by maissani** [comment]
@jaumard The job is done ;)
@tjwebb or @jaumard remeber to remove 

###### WARING : The current version of this trailpack is not available

from README.MD before publish.

**Comment by maissani** [comment]
Can you also add greenkeper.io bot to this repo ?

**Comment by jaumard** [comment]
`Missing Contributing and Licence section on the readme` :)

**Comment by maissani** [comment]
@jaumard  :) Thanx .  And now ?

**Comment by jaumard** [comment]
Perfect ;) :p

**Comment by jaumard** [comment]
Code climat url is wrong https://codeclimate.com/github/trailsjs/trailpack-cache

**Comment by jaumard** [comment]
@maissani you need to add this repo to at least trails maintainer team because no one have access to this repo except you :)

**Comment by maissani** [comment]
@jaumard :( I didn't realize that , All maintainers have now the access. Code climate link is fixed.
